### ISSUE TITLE
Test SolidusBraintree SSF update with Venmo Pay

### ISSUE THREAD

**Issue by gsmendoza** [solidusio/solidus_braintree#106]
## Blockers 

Depends on https://github.com/solidusio/solidus_braintree/pull/102. 

## Requirements

Tester might need to be in US. Wasn't successful in faking a Venmo payment. See https://github.com/solidusio/solidus_braintree/pull/102#issuecomment-1436467805.

**Comment by gsmendoza** [comment]
@kennyadsl Like you suggested a few days ago, I've been able to check out with Venmo in development by setting `force_buyer_country` to 'US'. Will document the steps later.

CC @RyanofWoods

**Comment by RyanofWoods** [comment]
I tried that, but it didn't work for me @gsmendoza 🤔

**Comment by gsmendoza** [comment]
@RyanofWoods Weird, I was able to get it working earlier. Note the saved Venmo payment method in my app:

![image](https://user-images.githubusercontent.com/61476/220873690-eb0a1814-df5f-4326-a4f2-f7744eb7808f.png)

Will continue to test.

**Comment by gsmendoza** [comment]
@kennyadsl @RyanofWoods I'm getting the "Merchant account does not support payment instrument. (91577) Payment instrument type is not accepted by this merchant account. (91517)" error now :( Will just try again tomorrow...

![image](https://user-images.githubusercontent.com/61476/220879603-3c89481e-928d-40e7-8b8d-780ac7a607e7.png)

**Comment by FrancescoAiello01** [comment]
Hey everyone, I was able to test it on my side since I'm located in the US. Here's how it went (going through the testing checklist):

**Ensure the Venmo checkout button opens a modal with a QR code and is closeable.**
This works as expected:
<details>
  <summary>Screenshots</summary>

<img width="1908" alt="Screenshot 2023-02-24 at 10 28 50 AM" src="https://user-images.githubusercontent.com/32208868/221260734-47cdc7a1-e187-4155-bf3e-9dbf7b072cc5.png">
<img width="1902" alt="Screenshot 2023-02-24 at 10 28 43 AM" src="https://user-images.githubusercontent.com/32208868/221260749-da8c2875-a3cc-49ef-8738-2ac6091a7cf7.png">
</details>

**Do a full transaction**
This works as expected:
<details>
  <summary>Screenshots</summary>
Scanning the QR code takes me here:
<img width="1907" alt="Screenshot 2023-02-24 at 10 30 29 AM" src="https://user-images.githubusercontent.com/32208868/221261310-ee11393e-b2ce-47d3-934a-96a6106b4dd3.png">

Clicking confirm succeeds:
<img width="1906" alt="Screenshot 2023-02-24 at 10 30 38 AM" src="https://user-images.githubusercontent.com/32208868/221261363-df76d676-1e25-4c9d-8c79-dfc788015079.png">
confirm succeeds:

</details>

**Ensure that you can also save the payment source in the user wallet.**

This works as expected. I'm also able to create another order in the admin interface using the user's saved payment source.

<details>
  <summary>Screenshots</summary>

<img width="540" alt="Screenshot 2023-02-24 at 10 33 15 AM" src="https://user-images.githubusercontent.com/32208868/221262299-00e981d0-b082-4180-8d9d-e913d731656e.png">


</details>

**Ensure the saved Venmo wallet payment source loads in the partial correctly.**

This looks right, but I'm not able to reuse the payment source on the user-facing flow:
<details>
  <summary>Screenshots</summary>

<img width="1908" alt="Screenshot 2023-02-24 at 10 34 58 AM" src="https://user-images.githubusercontent.com/32208868/221263029-e164764b-1074-46ca-93f0-11ad67658d4b.png">

</details>

**Ensure the saved Venmo payment source can be reused for another order.**

This only seems to work in the admin interface for me. In user-facing checkout I see the error in the above screenshot.

**Test doing transactions on the admin**

This works as expected:

<details>
  <summary>Screenshots</summary>

Order created via admin:
<img width="1915" alt="Screenshot 2023-02-24 at 10 27 18 AM" src="https://user-images.githubusercontent.com/32208868/221263278-64988cf3-7cc0-4f45-b26b-6e8e2cb7fd8b.png">

</details>

**Testing voiding and refunding Venmo transactions**

Voiding works as expected, but I'm not able to test refunding because the payment state is stuck on `Submitted For Settlement`. Not sure if that's a nuance with the sandbox environment 🤔

**Comment by FrancescoAiello01** [comment]
I'm not super familiar with Braintree or this gem, so I might have messed something up. LMK if you want me to re-test anything in any specific way!

**Comment by RyanofWoods** [comment]
The "all fields are empty error" seems to be due to the card form still being visible/not-disabled.

**Comment by gsmendoza** [comment]
Thanks for the excellent work @FrancescoAiello01 . I'll test if I can reproduce the "all fields are empty" error with PayPal checkout.

**Comment by FrancescoAiello01** [comment]
I paired with @elia and we found that the import maps weren't working correctly in the `solidus-starter-frontend`. Regenerating the sandbox app fixed it. We also found that the credit card iframe is still interactable when the fieldset is disabled, so we created a small PR to fix that: https://github.com/solidusio/solidus_starter_frontend/pull/326
